import Navigation from "@/components/navigation";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import { Inter, Open_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";

const os = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body style={os.style}>
          <ThemeProvider
          attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange>
            <Navigation />
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
